# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('identify', models.IntegerField(default='user_identify_id', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='user_name', max_length=32)),
                ('describe', models.CharField(default='user_describe', max_length=1000)),
                ('followings', models.TextField()),
                ('fans', models.TextField()),
                ('followings_number', models.IntegerField(default='user_followings_numbers')),
                ('fans_number', models.IntegerField(default='user_fans_numbers')),
                ('portrait', models.CharField(default='portrait_url', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='TravelComments',
            fields=[
                ('comments_id', models.AutoField(max_length=128, primary_key=True, serialize=False)),
                ('comments_datetime', models.DateTimeField(default='comments_time')),
                ('comment_f_id', models.IntegerField(default='comment_f_id')),
            ],
        ),
        migrations.CreateModel(
            name='Travels',
            fields=[
                ('travel_identify', models.IntegerField(default='travel_identify', primary_key=True, serialize=False)),
                ('travel_title', models.CharField(default='travel_title', max_length=1000)),
                ('travel_create_date', models.DateField(default='travel_create_date')),
                ('travel_view_number', models.IntegerField(default='travel_view_number')),
                ('travel_commended', models.BooleanField(default='travel_commend')),
                ('travel_when', models.DateField(default='travel_date')),
                ('travel_how_long', models.IntegerField(default='travel_spend_time')),
                ('travel_how_much', models.IntegerField(default='travel_cost')),
                ('travel_who', models.CharField(default='travel_who', max_length=30)),
                ('travel_how', models.CharField(default='travel_how', max_length=200)),
                ('travel_text', models.TextField(default='travel_content_text')),
                ('travel_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Persons')),
            ],
        ),
        migrations.AddField(
            model_name='travelcomments',
            name='comment_travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Travels'),
        ),
        migrations.AddField(
            model_name='travelcomments',
            name='comments_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Persons'),
        ),
    ]
